import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import NavWrapper from "@/components/navigation/NavWrapper";
import { createClient } from "@/lib/supabase/server";

const fontMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-mono antialiased dark",
          fontMono.variable
        )}
      >
        <NavWrapper>{children}</NavWrapper>

        <Toaster richColors theme="dark" />
      </body>
    </html>
  );
}
