import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { createClient } from "@/lib/supabase/server";
import TopNav from "@/components/navigation/TopNav";
import ReactQueryProvider from "@/components/ReactQueryProvider";

const fontMono = Roboto_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const supabase = createClient();
  const {
    data: { user },
    error,
  } = await supabase.auth.getUser();

  if (error) console.error(error);

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-mono antialiased dark",
          fontMono.variable
        )}
      >
        <ReactQueryProvider>
          {/* <NavWrapper>{children}</NavWrapper> */}

          <div className="flex flex-col min-h-screen">
            <TopNav user={user} />
            {children}
          </div>

          <Toaster richColors theme="dark" />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
